"use client";
import Image from "next/image";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Activity,ArrowUpRight,Check,ChevronRight,Code2,GitBranch,Link2,Play,RefreshCw,Search,ShieldCheck,TerminalSquare,Wallet} from "lucide-react";
import {connectWallet,currentAccount,isStudioNetwork,readJson,validAddress,watchNetwork,watchWallet,writeContract,type Encodable} from "@/lib/chain";
import {addressExplorer,defaultContract,txExplorer} from "@/lib/network";
type Pane="project"|"candidate"|"review"|"activate";
type Data=Record<string,unknown>;
const panes:{id:Pane;label:string}[]=[{id:"project",label:"Register sources"},{id:"candidate",label:"Bind revision graph"},{id:"review",label:"Verify on GitHub"},{id:"activate",label:"Activate revision"}];
const seed={projectId:"vault-domain",candidateId:"vault-domain.v2",dependencyRepo:"eaglebooth/forklens-dependency",consumerRepo:"eaglebooth/forklens-consumer",dependencyBase:"6cc2c3bf8aad0c0c23515e9ac01530c0d08243af",dependencyTarget:"59e9de2b40b74f287c0ad9cf2d1ccebf3b74b846",consumerBase:"1f22697154ae777b723b81df4fe043ae95d3a9d6",consumerTarget:"5113a6eac492e3d135601b2981f858803d094ae5",productionPaths:"src/vault-approval.js,package.json",testPaths:"test/vault-approval.test.js",attestation:""};
const s=(v:unknown)=>String(v??""); const n=(v:unknown)=>Number(v||0); const short=(v:string)=>v?`${v.slice(0,8)}…${v.slice(-6)}`:"—";
export default function Home(){
 const[contract,setContract]=useState(defaultContract());const[account,setAccount]=useState("");const[networkOk,setNetworkOk]=useState(false);const[pane,setPane]=useState<Pane>("project");const[f,setF]=useState(seed);const[project,setProject]=useState<Data|null>(null);const[candidate,setCandidate]=useState<Data|null>(null);const[stats,setStats]=useState<Data|null>(null);const[status,setStatus]=useState("IDLE");const[hash,setHash]=useState("");const[error,setError]=useState("");
 const set=(k:keyof typeof seed,v:string)=>setF(x=>({...x,[k]:v}));
 const sync=useCallback(async()=>{setError("");setStatus("READING");try{const[version,p,c,st]=await Promise.all([readJson(contract,"get_contract_version"),readJson(contract,"get_project",[f.projectId]),readJson(contract,"get_candidate",[f.candidateId]),readJson(contract,"get_stats")]);if(s(version.schema)!=="github-authoritative-dependency-gate-v3")throw new Error("Address is not ForkLens v3");setProject(p);setCandidate(c);setStats(st);if(s(c.attestation_digest))set("attestation",s(c.attestation_digest));setStatus("SYNCED")}catch(e){setStatus("ERROR");setError(e instanceof Error?e.message:String(e))}},[contract,f.projectId,f.candidateId]);
 useEffect(()=>{currentAccount().then(setAccount);isStudioNetwork().then(setNetworkOk);const stopWallet=watchWallet(a=>{setAccount(a);setStatus("WALLET_CHANGED")});const stopNetwork=watchNetwork(ok=>{setNetworkOk(ok);setStatus(ok?"NETWORK_READY":"WRONG_NETWORK")});return()=>{stopWallet();stopNetwork()}},[]);
 const owner=s(project?.owner).toLowerCase()===account.toLowerCase();
 const gate=useMemo(()=>{if(!validAddress(contract))return[false,"Enter a deployed ForkLens v2 contract"]as const;if(!account)return[false,"Connect a funded StudioNet wallet"]as const;if(!networkOk)return[false,"Switch wallet to GenLayer StudioNet · 61999"]as const;if(pane==="project")return[project?.exists!==true,"Register two distinct GitHub repository slugs"]as const;if(pane==="candidate")return[owner,"Owner binds exact base/head commits and required paths"]as const;if(pane==="review")return[candidate?.status==="SEALED","Any wallet may trigger GitHub-authoritative review"]as const;return[owner&&candidate?.status==="ATTESTED","Exact attestation activates one revision"]as const},[contract,account,networkOk,pane,project,candidate,owner]);
 async function submit(){setError("");if(!gate[0])return setError(gate[1]);let method="",args:Encodable[]=[];if(pane==="project"){method="register_project";args=[f.projectId,f.dependencyRepo,f.consumerRepo,f.dependencyBase,f.consumerBase]}else if(pane==="candidate"){method="open_candidate";args=[f.candidateId,f.projectId,f.dependencyBase,f.dependencyTarget,f.consumerBase,f.consumerTarget,f.productionPaths,f.testPaths]}else if(pane==="review"){method="assess_candidate";args=[f.candidateId]}else{method="activate_candidate";args=[f.candidateId,f.attestation]}
  try{const before=JSON.stringify(pane==="project"?project:candidate);const h=await writeContract(contract,account,method,args,(x,y)=>{setStatus(x);if(y)setHash(y)});setHash(h);const fresh=pane==="project"?await readJson(contract,"get_project",[f.projectId]):await readJson(contract,"get_candidate",[f.candidateId]);if(JSON.stringify(fresh)===before)throw new Error("Finalized, but authoritative state did not change");const ok=pane==="project"?fresh.exists===true:pane==="candidate"?fresh.status==="SEALED":pane==="review"?["ATTESTED","BLOCKED"].includes(s(fresh.status)):fresh.status==="ACTIVATED";if(!ok)throw new Error("Finalized, but expected transition was not confirmed");await sync();setStatus("VERIFIED")}catch(e){setStatus("ERROR");setError(e instanceof Error?e.message:String(e))}}
 const evidence=["DEPENDENCY COMPARE","CONSUMER COMPARE","CHANGED PATHS","EXACT-HEAD CHECKS"], active=panes.find(x=>x.id===pane)!;
 return <main>
  <header><div className="brand"><Image src="/forklens-logo.png" width={44} height={44} alt="ForkLens"/><div><b>FORKLENS</b><span>REVISION INTELLIGENCE</span></div></div><div className="command"><span><Activity/> STUDIONET · 61999</span><label><Search/><input value={contract} onChange={e=>setContract(e.target.value)} placeholder="Contract 0x…"/></label><button onClick={sync}><RefreshCw/>SYNC</button></div><button className="wallet" onClick={async()=>{try{setAccount(await connectWallet());setNetworkOk(true);setError("")}catch(e){setNetworkOk(false);setError(e instanceof Error?e.message:String(e))}}}><Wallet/>{account?(networkOk?short(account):"WRONG NETWORK"):"CONNECT"}</button></header>
  <section className="workspace">
   <aside className="graph"><div className="eyebrow">RELEASE GRAPH</div><h1>Trace the upgrade,<br/><em>not the claim.</em></h1><div className="branch"><div className="node base"><i/><span>DEPENDENCY BASE<small>{short(f.dependencyBase)}</small></span></div><div className="line"/><div className="node target"><i/><span>TARGET REVISION<small>{short(f.dependencyTarget)}</small></span></div><div className="fork"/><div className="node consumer"><i/><span>CONSUMER HEAD<small>{short(f.consumerTarget)}</small></span></div></div><div className="scope"><GitBranch/><span>PROJECT</span><b>{f.projectId}</b><small>EPOCH {n(project?.epoch)||"—"}</small></div><nav>{panes.map((x,i)=><button key={x.id} className={pane===x.id?"active":""} onClick={()=>setPane(x.id)}><span>{String(i+1).padStart(2,"0")}</span>{x.label}<ChevronRight/></button>)}</nav></aside>
   <section className="review"><div className="reviewHead"><div><span>ACTIVE PROCEDURE</span><h2>{active.label}</h2></div><div className={`badge ${s(candidate?.status).toLowerCase()}`}>{s(candidate?.status||"NOT SYNCED")}</div></div>
    <div className="diff"><div className="diffbar"><span><Code2/> DEPENDENCY DIFF</span><span>− removed</span><span>+ introduced</span></div><div className="code old"><i>−</i><code>verify(message, signature)</code></div><div className="code new"><i>+</i><code>verify(domain, message, signature)</code></div><div className="code new"><i>+</i><code>domain must bind chain + protocol</code></div></div>
    <div className="editor">{pane==="project"&&<><Field label="PROJECT ID" value={f.projectId} set={v=>set("projectId",v)}/><Field label="DEPENDENCY GITHUB SLUG (OWNER/REPO)" value={f.dependencyRepo} set={v=>set("dependencyRepo",v)}/><Field label="CONSUMER GITHUB SLUG (OWNER/REPO)" value={f.consumerRepo} set={v=>set("consumerRepo",v)}/><Field label="ACTIVE DEPENDENCY SHA" value={f.dependencyBase} set={v=>set("dependencyBase",v)}/><Field label="ACTIVE CONSUMER SHA" value={f.consumerBase} set={v=>set("consumerBase",v)}/></>}{pane==="candidate"&&<><Field label="CANDIDATE ID" value={f.candidateId} set={v=>set("candidateId",v)}/><Field label="DEPENDENCY TARGET SHA" value={f.dependencyTarget} set={v=>set("dependencyTarget",v)}/><Field label="CONSUMER TARGET SHA" value={f.consumerTarget} set={v=>set("consumerTarget",v)}/><Field label="PRODUCTION PATHS (COMMA-SEPARATED)" value={f.productionPaths} set={v=>set("productionPaths",v)}/><Field label="REGRESSION PATHS (COMMA-SEPARATED)" value={f.testPaths} set={v=>set("testPaths",v)}/></>}{pane==="review"&&<Summary icon={<Search/>} title="Verify authoritative GitHub facts" text="Validators independently fetch both exact commit comparisons, actual changed files and successful GitHub check-runs bound to the consumer head. Only then is semantic compatibility adjudicated."/>}{pane==="activate"&&<><Summary icon={<ShieldCheck/>} title="Consume one revision-bound attestation" text="Activation rechecks project ownership, epoch, both target revisions and the exact single-use attestation digest."/><Field label="ATTESTATION DIGEST" value={f.attestation} set={v=>set("attestation",v)}/></>}</div>
    <div className="actionbar"><div><span>CALLER POLICY</span><b>{gate[1]}</b></div><button disabled={!gate[0]} onClick={submit}><Play/>{pane==="review"?"RUN CONSENSUS":pane==="activate"?"ACTIVATE EXACT REVISION":"WRITE TO CONTRACT"}</button></div>
    {(status!=="IDLE"||error)&&<div className={`terminal ${error?"error":""}`}><TerminalSquare/><div><b>{error?"STOPPED":status}</b><span>{error||"Success appears only after FINALIZED consensus and exact state readback."}</span></div>{hash&&<a href={txExplorer(hash)} target="_blank">TX <ArrowUpRight/></a>}</div>}
   </section>
   <aside className="provenance"><div className="eyebrow">AUTHORITATIVE PROOF</div>{evidence.map((x,i)=>{const recorded=Boolean(candidate?.proof_digest);return <div className="evidence" key={x}><span>{String(i+1).padStart(2,"0")}</span><div><b>{x}</b><small>{recorded?"BOUND IN PROOF DIGEST":"FETCHED DURING REVIEW"}</small></div>{recorded?<Check/>:<i/>}</div>})}<div className="verdict"><span>SEMANTIC VERDICT</span><b>{s(candidate?.verdict||"UNASSESSED")}</b><p>{s(candidate?.summary||"The gate stays closed until GitHub independently proves exact revisions, changed implementation and tests, plus successful exact-head CI.")}</p></div><div className="stats"><div><small>PROJECTS</small><b>{n(stats?.projects)}</b></div><div><small>CANDIDATES</small><b>{n(stats?.candidates)}</b></div><div><small>OPEN ATTESTATIONS</small><b>{n(stats?.open_attestations)}</b></div></div>{contract&&<a className="contract" href={addressExplorer(contract)} target="_blank"><Link2/>ACTIVE CONTRACT <ArrowUpRight/></a>}</aside>
  </section>
  <footer><span>SELF-AUTHORED REPORT ≠ IMPLEMENTATION PROOF</span><span>FINALIZED · READBACK-VERIFIED · REVISION-BOUND</span></footer>
 </main>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>set(e.target.value)}/></label>}
function Summary({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="summary">{icon}<div><span>REVIEW CONTROL</span><h3>{title}</h3><p>{text}</p></div></div>}
